sudo: false

language: cpp

addons:
  apt:
    - cmake
    - lcov

matrix:
  include:
    - name: "linux-gcc-arm64"
      os: linux
      arch: arm64
      dist: bionic
      compiler: gcc
      env:
        - NAME=linux-gcc
        - BUILD="mkdir build && cd build && cmake -DCHAOSCV_TEST=ON .. && make -j2 && ctest --output-on-failure -j 2"

before_install:
  - eval "${BEFORE_BUILD}"

script:
  - eval "${BUILD}"