#pragma once

#include "core/core.hpp"
#include "core/tensor.hpp"

namespace chaos
{
	enum FrontFace
	{
		FRONT_FACE_COUNTER_CLOCKWISE = 0,
		FRONT_FACE_CLOCKWISE = 1,
		FRONT_FACE_MAX_ENUM = 0x7FFFFFFF
	};

	enum PolygonMode
	{
		POLYGON_MODE_FILL = 0,
		POLYGON_MODE_LINE = 1,
		POLYGON_MODE_POINT = 2,
		POLYGON_MODE_FILL_RECTANGLE_NV = 1000153000,
		POLYGON_MODE_MAX_ENUM = 0x7FFFFFFF
	};

	enum PrimitiveTopology {
		PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
		PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
		PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
		PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
		PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
		PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = 5,
		PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = 6,
		PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = 7,
		PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = 8,
		PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9,
		PRIMITIVE_TOPOLOGY_PATCH_LIST = 10,
		PRIMITIVE_TOPOLOGY_MAX_ENUM = 0x7FFFFFFF
	};


	CHAOS_API Tensor Rotate(const Tensor& m, const float angle, const Tensor& v);
	CHAOS_API Tensor LookAt(const Tensor& eye, const Tensor& center, const Tensor& up); // look at right hand
	CHAOS_API Tensor Perspective(float fovy, float aspect, float z_near, float z_far); // rh no
}