#name: windows|ubuntu|macos
name: windows|ubuntu

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/cmake.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/cmake.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: windows-latest
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest' ] # 'macos-latest'
      fail-fast: false

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    
    - name: Install googletest
      shell: bash
      run: |
        git clone https://github.com/google/googletest --depth 1
        cd googletest
        mkdir build && cd build
        if [ '${{runner.os}}' == 'Windows' ]; then
          echo "Yes, this is on Windows"
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}'/googletest-install -Dgtest_force_shared_crt=ON -G "Visual Studio 16 2019" -A x64
        else
          echo "Ohh, this is not on Windows"
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}'/googletest-install -G Ninja
        fi
        cmake --build . --config ${{env.BUILD_TYPE}} -j 2
        cmake --install . --config ${{env.BUILD_TYPE}}
          
    - name: Configure with CMake
      #run: cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      shell: bash
      run: |
        mkdir build
        cd build
        #cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        if [ '${{runner.os}}' == 'Windows' ]; then
          cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        else
          cmake -G Ninja .. -DCHAOS_EXPORT=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        fi
 
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Testing
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      
