#name: windows|ubuntu|macos
name: dev.ubuntu

on:
  push:
    branches: [ dev ]
    paths:
    - '.github/workflows/cmake.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3
    
    - name: Install googletest
      shell: bash
      run: |
        git clone https://github.com/google/googletest --depth 1
        cd googletest
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}'/googletest-install -G Ninja
        cmake --build . --config ${{env.BUILD_TYPE}} -j 2
        cmake --install . --config ${{env.BUILD_TYPE}}
          
    - name: Configure with CMake
      #run: cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -G Ninja .. -DCHAOSCV_TEST=ON -DGTest_DIR=${{github.workspace}}/googletest-install/lib/cmake/GTest -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
 
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Testing
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure