name: test-coverage
on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/test-coverage.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'
  pull_request:
    branches: [main]
    paths:
    - '.github/workflows/test-coverage.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug


jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: install google test
      run: |
        git clone https://github.com/google/googletest --depth 1
        cd googletest
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/gtest' ..
        cmake --build . --config ${{env.BUILD_TYPE}}
        cmake --install . --config ${{env.BUILD_TYPE}}
    - name: lcov
      run: sudo apt-get install lcov
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCHAOS_COVERAGE=ON -DCHAOS_BUILD_TESTS=ON -DGTest_DIR=${{github.workspace}}/gtest/lib/cmake/GTest ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest --output-on-failure
    - name: lcov-collect
      run: |
        cd build
        lcov -d . -c -o lcov.info
        lcov -r lcov.info '*/ChaosCV/**' -o lcov.info
        lcov -r lcov.info '*/build/*' -o lcov.info
        lcov -r lcov.info '/usr/*' -o lcov.info
        lcov --list lcov.info
    - name: codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build/lcov.info
