name: test-coverage
on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/test-coverage.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'
  pull_request:
    branches: [main]
    paths:
    - '.github/workflows/test-coverage.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'
    
jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Clone repository
      uses: actions/checkout@v2
    - name: lcov
      run: sudo apt-get install lcov
    - name: Install googletest
      shell: bash
      run: |
        git clone https://github.com/google/googletest --depth 1
        cd googletest
        mkdir build && cd build
        if [ '${{runner.os}}' == 'Windows' ]; then
          echo "Yes, this is on Windows"
          cmake .. -DCMAKE_BUILD_TYPE=env.BUILDTYPE−DCMAKEINSTALLPREFIX=′{{github.workspace}}'/googletest-install -Dgtest_force_shared_crt=ON -G "Visual Studio 16 2019" -A x64
        else
          echo "Ohh, this is not on Windows"
          cmake .. -DCMAKE_BUILD_TYPE=env.BUILDTYPE−DCMAKEINSTALLPREFIX=′{{github.workspace}}'/googletest-install -G Ninja
        fi
        cmake --build . --config ${{env.BUILD_TYPE}} -j 2
        cmake --install . --config ${{env.BUILD_TYPE}}
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=debug -DCHAOSCV_COVERAGE=ON -DCHAOSCV_TEST=ON ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest --output-on-failure
    - name: lcov-collect
      run: |
        cd build
        lcov -d ./ -c -o lcov.info
        lcov -r lcov.info '*/ChaosCV/*' -o lcov.info
        lcov --list lcov.info
    - name: codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: build/lcov.info
