#name: windows|ubuntu|macos
name: ubuntu

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/cmake.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/cmake.yml'
    - 'CMakeLists.txt'
    - 'Inception/ChaosCV/**'
    - 'Tests/GTests/*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.image }}
    #strategy:
    #  matrix:
    #    image: [ 'windows-latest', 'ubuntu-latest' ] # 'macos-latest'
    #  fail-fast: false

    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: install google test
      run: |
        git clone https://github.com/google/googletest --depth 1
        cd googletest
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/gtest' ..
        cmake --build . --config ${{env.BUILD_TYPE}}
        cmake --install . --config ${{env.BUILD_TYPE}}
    - name: build
      run: |
        mkdir build && cd build
        cmake -DCHAOS_BUILD_TESTS=ON ..
        cmake --build .
    - name: test
      run: cd build && ctest --output-on-failure
